openapi: 3.0.3
info:
  title: Yes-Man LangFlow Integration API
  description: LangFlowエージェントとの統合API
  version: 1.0.0
  
servers:
  - url: http://localhost:8002
    description: LangFlow統合API
    
paths:
  /langflow/execute_flow:
    post:
      summary: エージェントフロー実行
      description: Yes-Manエージェントフローを実行してユーザー入力に応答
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_input
                - session_id
              properties:
                user_input:
                  type: string
                  description: ユーザーの音声入力テキスト
                session_id:
                  type: string
                  format: uuid
                  description: 会話セッションID
                flow_name:
                  type: string
                  default: "yes_man_agent"
                  description: 実行するフロー名
                context:
                  type: object
                  description: 会話コンテキスト
                  properties:
                    previous_exchanges:
                      type: array
                      items:
                        type: object
                        properties:
                          user_input:
                            type: string
                          agent_response:
                            type: string
                          timestamp:
                            type: string
                            format: date-time
                    current_tools:
                      type: array
                      items:
                        type: string
      responses:
        '200':
          description: フロー実行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_response:
                    type: string
                    description: Yes-Manエージェントの応答
                  response_time_ms:
                    type: integer
                    description: 処理時間（ミリ秒）
                  tools_used:
                    type: array
                    items:
                      type: string
                    description: 使用されたツールのリスト
                  flow_execution_id:
                    type: string
                    description: フロー実行ID
                  metadata:
                    type: object
                    properties:
                      yes_man_mood:
                        type: string
                        enum: ["happy", "excited", "helpful", "confused"]
                      confidence_score:
                        type: number
                        minimum: 0.0
                        maximum: 1.0
        '400':
          description: 無効な入力パラメータ
        '503':
          description: LangFlowサービス利用不可

  /langflow/get_available_tools:
    get:
      summary: 利用可能ツール一覧取得
      description: 現在有効化されているツールの一覧を取得
      responses:
        '200':
          description: ツール一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  tools:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        is_enabled:
                          type: boolean
                        priority_order:
                          type: integer
                        usage_count:
                          type: integer

  /langflow/update_tool_status:
    post:
      summary: ツール有効/無効切り替え
      description: 指定ツールの有効/無効状態を変更
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tool_name
                - is_enabled
              properties:
                tool_name:
                  type: string
                is_enabled:
                  type: boolean
                priority_order:
                  type: integer
      responses:
        '200':
          description: ツール状態更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  tool_name:
                    type: string
                  is_enabled:
                    type: boolean
                  updated_at:
                    type: string
                    format: date-time

  /langflow/get_agent_settings:
    get:
      summary: エージェント設定取得
      description: Yes-Manエージェントの現在の設定を取得
      responses:
        '200':
          description: エージェント設定
          content:
            application/json:
              schema:
                type: object
                properties:
                  personality_prompt:
                    type: string
                  response_style:
                    type: string
                    enum: ["enthusiastic", "helpful", "casual"]
                  max_response_length:
                    type: integer
                  context_memory_turns:
                    type: integer
                  custom_prompts:
                    type: object

  /langflow/update_agent_settings:
    post:
      summary: エージェント設定更新
      description: Yes-Manエージェントの設定を更新
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                personality_prompt:
                  type: string
                response_style:
                  type: string
                  enum: ["enthusiastic", "helpful", "casual"]
                max_response_length:
                  type: integer
                  minimum: 50
                  maximum: 1000
                context_memory_turns:
                  type: integer
                  minimum: 1
                  maximum: 20
                custom_prompts:
                  type: object
      responses:
        '200':
          description: 設定更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_settings:
                    type: object
                  updated_at:
                    type: string
                    format: date-time

  /langflow/conversation_history:
    get:
      summary: 会話履歴取得
      description: 指定セッションまたは全体の会話履歴を取得
      parameters:
        - name: session_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: 特定セッションID（省略時は全履歴）
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 500
        - name: since
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: この日時以降の履歴
      responses:
        '200':
          description: 会話履歴
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      type: object
                      properties:
                        session_id:
                          type: string
                          format: uuid
                        timestamp:
                          type: string
                          format: date-time
                        user_input:
                          type: string
                        agent_response:
                          type: string
                        response_time_ms:
                          type: integer
                        tools_used:
                          type: array
                          items:
                            type: string
                  total_count:
                    type: integer
                  has_more:
                    type: boolean

  /langflow/health:
    get:
      summary: LangFlow統合ヘルスチェック
      description: LangFlowサービスとの接続状態を確認
      responses:
        '200':
          description: サービス正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["healthy"]
                  langflow_version:
                    type: string
                  database_connected:
                    type: boolean
                  yes_man_flow_loaded:
                    type: boolean
                  uptime_seconds:
                    type: integer

components:
  schemas:
    LangFlowError:
      type: object
      properties:
        error:
          type: string
        error_code:
          type: string
          enum: ["FLOW_NOT_FOUND", "EXECUTION_ERROR", "DATABASE_ERROR", "TOOL_ERROR"]
        details:
          type: string
        execution_trace:
          type: array
          items:
            type: string